[package]
name = "raycasting-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = {git = "https://github.com/rust-windowing/winit.git"}
anyhow = "1.0.86"
log = "0.4.22"
softbuffer = "0.4.5"
image = "0.25.1"